#!/bin/bash

sxhkd & 

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1-0"

# On first load, set up default workspaces
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
fi

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --rotate normal --output "$EXTERNAL_MONITOR" --mode 1920x1080 --rotate normal --right-of "$INTERNAL_MONITOR"
fi

~/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap           30
bspc config focused_border_color "#a9b665"
bspc config normal_border_color "#d8a657"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
